# serverless.yml

service: minifarm-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2
  memorySize: 128
  timeout: 6

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: npm

package:
  individually: true

functions:
  app:
    handler: src/app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  